### PR TITLE
Update Mattermost and mmctl to 6.1.0

### PR DESCRIPTION
**Pull request by kemenaran**

### CODE REVIEW

**Comment by kemenaran** [comment]
I don't understand why dependabot doesn't open prs anymore.

@parnic-sks do you know how by chance to debug dependabot? Are they logs somewhere?

**Comment by parnic-sks** [comment]
Yeah - Insights, Dependency Graph, "Last checked" link will show a log.
https://github.com/SmartHoneybee/ubiquitous-memory/network/updates -> https://github.com/SmartHoneybee/ubiquitous-memory/network/updates/237068203

I don't know why it's getting worked up over mmctl's version, though.

**Comment by kemenaran** [comment]
@parnic-sks thanks! I'm trying some changes to see if it fixes the detection.

**Comment by kemenaran** [comment]
It builds! Let's try this.

**Pull request merged**
